apiVersion: v1
kind: Service
metadata:
  name: library-management-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: library-management-system
